# Generated by Django 2.0.7 on 2018-07-22 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Free', 'Free'), ('Small', 'Small'), ('Standard', 'Standard'), ('Ultimate', 'Ultimate')], max_length=100, unique=True)),
                ('duration', models.IntegerField(default=1)),
                ('date_introduced', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('number_of_downloads', models.PositiveIntegerField(default=4)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
