# Generated by Django 2.0.7 on 2018-07-22 22:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('level', models.CharField(blank=True, choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.College')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('number_of_downloads', models.IntegerField(default=0)),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('question_file', models.FileField(blank=True, upload_to=home.models.Question.question_directory_path)),
                ('solution_file', models.FileField(blank=True, upload_to=home.models.Question.solution_directory_path)),
                ('question_type', models.CharField(choices=[('Free', 'Free'), ('premium', 'Premium'), ('Others', 'others')], max_length=10)),
                ('quiz_number', models.CharField(choices=[('quiz 1', ' quiz 1'), ('quiz 2', 'quiz 2'), ('exams', 'examination'), ('supplementary', 'supplementary')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ManyToManyField(to='home.Programme'),
        ),
    ]
