# Generated by Django 2.0.7 on 2019-01-21 19:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_question_page1'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='page2',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='page3',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='page4',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='page1',
            field=tinymce.models.HTMLField(blank=True, default='aaaaa', null=True),
        ),
    ]
