# Generated by Django 2.0.7 on 2019-01-21 19:25

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190121_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='page1',
            field=tinymce.models.HTMLField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
