# Generated by Django 2.0.7 on 2018-07-25 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptionpackages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchased', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_downloads', models.PositiveIntegerField(default=0)),
                ('downloads_left', models.PositiveIntegerField(default=0)),
                ('subscription_package', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptionpackages.SubscriptionPackage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
